name: Fallout
main: com.luzinsk.fallout.Fallout
version: 1.0
api-version: 1.14
description: not available
author: Carlton
commands:
  m4:
    description: gives you an m4
  m97:
    description: gives you an m97
  awp:
    description: gives you an awp
  topaz:
    description: gives you a topaz
  ammo:
    description: shows how much ammo you have
  test:
    description: testing
