name: Fallout
main: com.luzinsk.fallout.Fallout
version: 1.0
api-version: 1.14
description: not available
author: Carlton
commands:
  m16:
    description: gives you a crossbow
  awp:
    description: gives you an awp
  ammo:
    description: shows how much ammo you have
  test:
    description: testing